name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up a PureScript toolchain
        uses: purescript-contrib/setup-purescript@main
        with:
          purescript: "latest"
          purs-tidy: "latest"
          spago: "unstable"

      - name: Cache PureScript dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-spago-${{ hashFiles('**/spago.lock') }}
          path: |
            .spago
            output

      - name: Setup node and npm
        uses: actions/setup-node@v4

      - name: Cache NPM dependencies
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}-
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM dependencies
        run: npm install

      - name: Build source
        run: spago build --censor-stats --strict --ensure-ranges --pedantic-packages

      - name: Run tests
        run: spago test --offline --censor-stats --strict --pedantic-packages -- --censor-codes=UserDefinedWarning

      - name: Verify formatting
        run: purs-tidy check src test
